### PR TITLE
OSX specific instructions. Specify min docker version

### PR DESCRIPTION
**Pull request by tigerlily-he**
Adjusting memory and CPU only required for OSX. Fixes https://github.com/pelias/dockerfiles/pull/1#pullrequestreview-45952104 

Linked to pelias/pelias repo at top

Part of https://github.com/pelias/pelias/issues/596

### CODE REVIEW

**Comment by missinglink** [comment]
hey, I think the nested list syntax for markdown isn't quite right, it should be something like this:

```bash
1. Dog
    1. German Shepherd
    2. Belgian Shepherd
        1. Malinois
        2. Groenendael
        3. Tervuren
2. Cat
    1. Siberian
    2. Siamese
```

I noticed in the github preview it doesn't nest like I think you wanted it to?

**Comment by missinglink** [comment]
in the part which says:

```
A /tmp/data directory for storing downloaded datasets
```

maybe we can just say 'a directory', the creation is covered in the `Create a Directory for Your Data` section. readers might be confused that the directory must be located at `/tmp/data` or that the directory must be temporary.

**Review by missinglink — CHANGES_REQUESTED** [review]
couple small changes, otherwise LGTM!

**Comment by tigerlily-he** [comment]
Formatting for nested lists fixed. Github automatically increments so having 
```
1. Dog
    1. German Shepherd
    1. Belgian Shepherd
        1. Malinois
        1. Groenendael
        1. Tervuren
```
works as well.

**Pull request merged**
